version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"        # 👈 backend en 5000
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"        # 👈 frontend en 3000
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000   # 👈 conectar con backend interno
    networks:
      - app-network
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
